### ISSUE TITLE
希望增加cookie失效通知

### ISSUE THREAD

**Issue by czcmh** [chengquanomg/iqy_checkin#1]
各方面都很完美，感谢大佬，要是有个cookie失效通知就更好了

**Comment by chengquanomg** [comment]
主要是抽奖的cookie会失效吧 签到一直能用  有空加

**Comment by moxinshi** [comment]
为什么我在腾讯云上跑不起来，总是报错

**Comment by moxinshi** [comment]
{"errorCode":-1,"errorMessage":"Runtime.UserCodeSyntaxError: SyntaxError: /var/user/config.json: Unexpected token d in JSON at position 16\n    at Object.module.exports.load (/var/runtime/node12/UserFunction.js:32:13)\n    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:96:38)\n    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)","requestId":"d210656d-5652-4119-af78-0866a49541b6","statusCode":443}

**Comment by chengquanomg** [comment]
> {"errorCode":-1,"errorMessage":"Runtime.UserCodeSyntaxError: SyntaxError: /var/user/config.json: Unexpected token d in JSON at position 16\n at Object.module.exports.load (/var/runtime/node12/UserFunction.js:32:13)\n at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:96:38)\n at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)\n at listOnTimeout (internal/timers.js:549:17)\n at processTimers (internal/timers.js:492:7)","requestId":"d210656d-5652-4119-af78-0866a49541b6","statusCode":443}

config.json里的格式不对

**Comment by hejun041** [comment]
![image](https://user-images.githubusercontent.com/16474051/126284406-6d3c319b-b1aa-47e8-8772-feae43414040.png)
异常是什么问题呢，抽奖cookie失效了吗

**Comment by chengquanomg** [comment]
> ![image](https://user-images.githubusercontent.com/16474051/126284406-6d3c319b-b1aa-47e8-8772-feae43414040.png)
> 异常是什么问题呢，抽奖cookie失效了吗

对的

**Comment by chengquanomg** [comment]
已添加通知
