### ISSUE TITLE
程序无法使用

### ISSUE THREAD

**Issue by jsk188** [chengquanomg/iqy_checkin#3]
日志如下图所示
![image](https://user-images.githubusercontent.com/91103853/152945362-5dd09d1e-780a-4fc7-a8de-917d59ebd0d1.png)

**Comment by cyd** [comment]
签到的不行了。这边代码改改，其它还是能用：
`    
.then(res => { 
    //res.data.data.todayGrowth
      console.log("今日签到成长值：" + JSON.stringify(res.data))
})
`
