### ISSUE TITLE
运行部分后报错

### ISSUE THREAD

**Issue by RouJiANG-14** [chengquanomg/iqy_checkin#5]
cookie0[object Object]
{ code: 0, isTarget: 0, daysurpluschance: '0', isSendGift: 0 }
cookie0：iqy今日已抽奖
cookie0：已完成每日观影成就
cookie0：领取浏览会员兑换活动任务成功
cookie0：完成浏览会员兑换活动任务成功
cookie0：领取浏览会员兑换活动任务奖励成功, 获得+1点成长值
cookie0：已完成逛领福利频道
/ql/data/scripts/chengquanomg_iqy_checkin/index.js:76
  for (let index = 0; index < parseCookies.length; i++) {
                                                    ^

ReferenceError: i is not defined
    at sign (/ql/data/scripts/chengquanomg_iqy_checkin/index.js:76:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.3.0

**Comment by RouJiANG-14** [comment]
希望大佬帮忙费心看一下怎么回事。

**Comment by chengquanomg** [comment]
好了。。改漏了

**Comment by RouJiANG-14** [comment]
感谢老哥！！！
